[tool.poetry]
name = "hello-gha-workflow-command"
version = "0.1.0"
description = ""
authors = ["cm-fujikawa <fujikawa.takuji@classmethod.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
